import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";
import { GameProvider } from "./hooks/GameProvider";
import { Toaster } from "sonner";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="purple">
      <ThemeProvider>
        <GameProvider>
          <ConfigProvider
            theme={{
              token: {
                colorPrimary: "var(--color-primary)",
              },
            }}
          >
            <body
              className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
              {children}
              <Toaster position="top-center" />
            </body>
          </ConfigProvider>
        </GameProvider>
      </ThemeProvider>
    </html>
  );
}
